KOBO_API_TOKEN = "5723a0f5b9b01dfda17940cd8f1701beb21b6619"
KOBO_ASSET_ID = "aqjgNoL4WiESEEfQ9Sj9DL"
KOBO_MONITORING_ASSET_ID = "aDSNfsXbXygrn8rwKog5Yd"
KOBO_MONITORING_ASSET = "dXdb36aV"

SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_USERNAME = "kabasil81@gmail.com"
SMTP_PASSWORD = "akhz lokt fvti ugnd"
APP_URL = "http://localhost:8501"



[FIREBASE]
TYPE = "service_account"
PROJECT_ID = "carbontally-b7227"
PRIVATE_KEY_ID = "74c180322fddfaa0a7cc934eb69edd8f82bbba93"
PRIVATE_KEY = '''-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCUWCYQPjXg6tzY
UHImnCRKItenMLQ9kJVE0brbSUQT88AuUR7H1ST6BPcxa8yDIbITg8jp6cw9YlqG
fd4g42JnRPiwiQyONMLWLBpCWrGWMVA4ysquYHP3OWSL5y4soaax1eoZV+osYc9H
eJ2PtsgFVcHoQcl9IrT0NuWsJJSusEU4uCAqNpcSsCXGeMuiy5ZsvIbN4PdCwI8e
8z9wNtKSkarMuhosWQsWoMD1pZreoAY7zJCBcl5OJxwXKzoHPtPu21VIZkSuiTID
JTT8BxcKADhqDpB4y58Yp85Ue34ApDgePWPH6kW53XZLA+Kl6NXgbviXonUy6/Ts
9VpIdqYnAgMBAAECggEAD+9oJ1aHcyHHl3UMzhj3zP7xK4SP2A0v+7SL3gKAzaPh
gRg1tkGvNyxRYX2y+mMkPfRqILZ8uhtWnhvnQKEscOt3y37tWllQlLEoIPidGwUx
GOiv3Qt/aY9AvcaXrzOuNGxGOXK4NQxMt+C9DDMWSXxs2AY5HrgbuCAti9BiKGGd
LVXXhk7qaz8g6oOBOjnGDTNTfNmRC0mvhvPHYEisFlyOvjtHDOt7vmdqft7uWHUe
LZvWPIhrDiYWopnofZN54TSvAgQdemHAqb0Hz6/2v7d7++4MjhamFhi6Q/qTb+b9
5ic9I1KSXiTgFAwQiLhFSJ/kfWvQGry0RBxTAnlIAQKBgQDHKNWLMUTVEQS1Ejcu
S2eAvklSsCkbbWPLJd/+UVVzn80z13Pr7NcmJJtuujhwINDC2optgo34GqFcCDA1
2/O8Xn59HJllI+o2dVCwzBCwPTeZAfnnDFbUtJJb8EynKLKKr9J5nVUU8ssC2Rtx
7qDUXSwP3ArKtMDIsHloTFJnyQKBgQC+rpyWRqx+ulc3VddL+CeQxfarYeXmITC8
YtiNMOo66STcYkqkpBHexIYpRrhSnkP3pPeGLqZzWCKqzA07K3CjnKISsOxPTiPR
PslnzDBZbgL1+SugQUkAnk8InsVCrkF3bREx7YCetxl/VrPo+nO3AejVDHRD2ss1
hAa9qj12bwKBgE+KMW776F+oAldGxR8KInY6iRIrJN+9WoPBxqnNVfFtuwifXb61
wl+Lc0BPw0aU9Is9uNdvsr+J8zPMWWTJSZjLrHzPNTw9kcbaJ7XUaj3Y1SGYtnPe
a7dbvrBVUmfYSyY0fjzv5xEMvqOOjfV8tmLaK0TSPsUiV3RPds1+3dJxAoGBAIrX
Cy8koJ7ZwX2KJGytcOmqKzSY4NPS4PCarIEJ19MzRWKusxj0WgqxX9qYIsgNcwHT
fWOXfh1IVF22m/+0XpzTBPPFHRuVkuDd7bqFY8MKJl/BoTFbt/MaUgO9z3YA+awi
nz2SaG+odIlSsUb3beAYJNdT7SgnHIWH73yUg5JDAoGBAK0of2Wje7jqWFfoX4j5
IcqO2I8d2dQ3hKD4Un0FHmmyvaM1V9nNJz/sAinLpiTSv/LvbLGUVxCb3lCgXu1h
hfQWF9Dk3jmtg2XRwZjqKf5LbcwLWEp1f4h9xB47dTcVB1MsugjgB5nn1Vv9iSNB
4OCE+9VQgtmnA//ZOi8S3OMS
-----END PRIVATE KEY-----'''
CLIENT_EMAIL = "firebase-adminsdk-fbsvc@carbontally-b7227.iam.gserviceaccount.com"
CLIENT_ID = "103599329433600893335"
AUTH_URI = "https://accounts.google.com/o/oauth2/auth"
TOKEN_URI = "https://oauth2.googleapis.com/token"
AUTH_PROVIDER_X509_CERT_URL = "https://www.googleapis.com/oauth2/v1/certs"
CLIENT_X509_CERT_URL = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40carbontally-b7227.iam.gserviceaccount.com"
UNIVERSE_DOMAIN = "googleapis.com"



